[project]
name = "segmenter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Robert Slater", email = "rdslater@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.6",
    "pillow>=12.3.0",
    "pydicom>=3.0.2",
    "pytorch-lightning>=2.6.6",
    "segmentation-models-pytorch>=0.5.0",
    "torch>=2.14.0",
    "torchmetrics>=1.9.0",
]

[project.scripts]
segmenter = "segmenter:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
